### ISSUE TITLE
请问我需要在哪里mock getuid这个函数 还有stat，mkdir函数等..

### ISSUE THREAD

**Issue by cpsky** [lucklove/tidb-wasm#6]
这是我的异常栈

panic: syscall/js: call of Value.Call on undefined
wasm_exec.js:41 
wasm_exec.js:41 goroutine 1 [running]:
wasm_exec.js:41 syscall/js.Value.Call(0x0, 0x1ca996, 0x6, 0x0, 0x0, 0x0, 0x41b80002)
wasm_exec.js:41 	D:/Go/src/syscall/js/js.go:318 +0x7f
wasm_exec.js:41 syscall.Getuid(0x10e7200)
wasm_exec.js:41 	D:/Go/src/syscall/syscall_js.go:285 +0x2
wasm_exec.js:41 os.Getuid(0x390260)
wasm_exec.js:41 	D:/Go/src/os/proc.go:30 +0x2
wasm_exec.js:41 github.com/satori/go%2euuid.init()
wasm_exec.js:41

**Comment by lucklove** [comment]
啊～不好意思现在才回复，现在这个项目已经在往 [tidb](https://github.com/pingcap/tidb/tree/feature/wasm) 合并了，直接用那个版本吧，那个更完善些，我更新下 README

**Comment by lucklove** [comment]
README 已更新，可以参考 README 操作，目前已知 go1.13 的 Wasm 支持有些 bug , 只能用 go1.12 或者 go master 编译运行

如果还有其他问题可以在 [这里](https://github.com/pingcap/tidb/pull/13069) 反馈

**Comment by cpsky** [comment]
多谢~
